Emobilis/urls.py
from django.contrib import admin
from django.urls import include, path


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # creating a default path
    path('', include("teachers.urls")),
    path('settings', include("settings.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settings/urls.py
from django.urls import path
from . import views

app_name= "settings"
urlpatterns =[

    path('', views.home, name="settings")

]

teachers/urls.py
from django.urls import path
from . import views

app_name="teachers"
urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path('add/', views.add, name="addData"),
    path('viewdata/', views.viewdata, name="viewdata"),
    path('delete/<id>',views.delete, name="delete"),
    path('insert/', views.insertdata, name="insertdata"),
    path('edit/<id>', views.edit, name="edit"),
    path('sliders/',views.sliders, name="sliders"),
    path('search/', views.search, name="search"),
    # path for class based views:
    path('register/', views.SignUpview.as_view(), name='register'),
    path('login/', views.Userlogin.as_view(), name="login")

]

settings/models.py
from django.db import models

# Create your models here.

teachers/models.py
from django.db import models

#for user accounts and authentication:
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Students(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    email = models.EmailField(blank=False)
    phone = models.IntegerField()
    image = models.ImageField(upload_to="uploads/images", default="uploads/images/profile.jpg")

    def __str__(self):
        return self.name


class Sliders(models.Model):
    text = models.CharField(max_length=100, blank=False, null=False)
    text1 = models.CharField(max_length=100, blank=False, null=False)
    image = models.ImageField(upload_to="uploads/sliders", default="uploads/sliders/profile.jpg")

    def __str__(self):
        return self.text



#custom class for user registration
#A
class CustomUser(AbstractUser):
    year = models.PositiveIntegerField(blank=True, null=True)






# any minute you modify the models file you must make and run migrations
# python manage.py makemigrations: make migrations - creates the table(model) in database
# python manage.py migrate: running migrations - updates the table/model

settings/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'settings.html')

teachers/views.py
from django.shortcuts import render, redirect
from .models import Students, Sliders, CustomUser

from django.http import HttpResponse

#for alerts import
from django.contrib import messages
from django.core.paginator import Paginator


#imports for class based views . Useraccounts and authentication
from django.views.generic import CreateView
from . form import  CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.

def home(request):
    return render(request, 'home.html', {'navbar': 'home'})


def about(request):
    return render(request, 'about.html', {'navbar': 'about'})


def contact(request):
    return render(request, 'contact.html', {'navbar': 'contact'})


def add(request):
    return render(request, "add.html", {'navbar': 'add'})


#def viewdata(request):
    # retrieving data from db and storing it in a variable . lets call the variable data
    #data = Students.objects.all()
    #return render(request, "viewdata.html", {'navbar': 'viewdata', 'data': data})

#adding paginations
def viewdata(request):
    #getting all items and specifying how many items should be there per page and storing them in a variable calle dpaginate
    paginate = Paginator(Students.objects.all(),2)
    page = request.GET.get('page')
    data = paginate.get_page(page)
    return render(request, "viewdata.html", {'navbar': 'viewdata', 'data': data})





def delete(request, id):
    std = Students.objects.get(id=id)
    std.delete()

    messages.warning(request, "Record deleted successfully")
    return redirect("/viewdata")


# writing a function that enables user entered data to be stored in db

def insertdata(request):
    # verifying if form method is post
    if request.method == "POST":
        # if yes gets the user input  and stores them  in a variable ith the same exact name as the input
        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")

        # for image
        # checking if image is existing
        if len(request.FILES) != 0:
            image = request.FILES['image']

        # creating a variable that matches the columns in the model Students with the variable names we have above
        query = Students(name=name, email=email, phone=phone, image=image)
        # after comparing save everything in query using save()method
        query.save()

        # for alerts. Message below shows if saved successfully

        messages.success(request, "Record added successfully")

        return redirect("/viewdata")
    return redirect("/viewdata")
    # make sure to call this function in the form action attribute.
    # pass the insertdata path to it


# editing data
def edit(request, id):
    # verifying if form method is post

    if request.method == "POST":

        # get the newly keyed-in values

        name = request.POST.get("name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")

        # for image
        # checking if image is existing
        if len(request.FILES) != 0:
            image = request.FILES['image']

        # getting existing data
        student = Students.objects.get(id=id)

        # replacing the existing data with the new value

        student.name = name
        student.email = email
        student.phone = phone
        student.image = image

        student.save()
        messages.success(request,"Record updated Successfully")
        return redirect("/viewdata")

    student = Students.objects.get(id=id)
    return render(request, "edit.html", {'student': student})


def sliders(request):
    slides = Sliders.objects.all()
    return render(request, 'sliders.html', {'navbar': 'sliders', 'slides':slides})



#searching in django
def search(request):
    if request.method =='GET':
        # argument passed to get method should  be the same as the input field name
        query = request.GET.get('query')
        if query:
            student = Students.objects.filter(name__icontains=query)
            return render(request,'search.html',{'data':student}) # in the context the key should be the same name as the variable name used to loop while viewing the data in the database. Check for loop in html file


class SignUpview(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    # specifies path to be redirected to after successful registration
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class Userlogin(LoginView):
    template_name = 'login.html'

settings/templates/settings.html
{% extends 'layout.html' %}


{% block body %}

    <title>Settings</title>

    <p class="one"> this is the settings app</p>
{% endblock %}

teachers/templates/about.html
{% extends  'layout.html' %}

{% block body  %}
 <title>About</title>


    <p>all data must go within the block</p>

{% endblock %}

teachers/templates/add.html
{% extends 'layout.html' %}

{% block body %}

    <title>Add Data</title>


<div class="row container">
<div class="col-md-6">
    <br><br>
    <form action="/insert/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="p-3">Add Student</h2>
        <div class="mb-3">
        <label  class="form-label">Name</label>
        <input type="text" class="form-control" name="name"  placeholder="Name" required>
    </div>

    <div class="mb-3">
        <label  class="form-label">Email</label>
        <input type="text" class="form-control"  name="email" placeholder="Email" required>

    </div>

    <div class="mb-3">
        <label  class="form-label">Phone Number</label>
        <input type="number" class="form-control" name="phone"  placeholder="Number" required>

    </div>

    <div class="mb-3">
        <label  class="form-label">image</label>
        <input accept="image/png, image/gif, image/jpeg" name="image" type="file" class="form-control"  placeholder="Add image" required>

    </div>

    <div class="mb-3">

        <button type="submit" name="button" class="form-control btn btn-success" >Submit</button>


    </div>

    </form>

</div>
</div>



{% endblock %}

teachers/templates/contact.html
{%  extends 'layout.html' %}

{% block body  %}
 <title>Contact</title>

    <div class="container row">
        <div class="col-md-6">
          <form action="">
                <div class="mb-3">
                   <label  class="form-label">Name</label>
                    <input type="text" class="form-control" name="name-contact"  placeholder="Name" required>
                </div>

                <div class="mb-3">
                   <label  class="form-label">Email</label>
                    <input type="text" class="form-control" name="email-contact"  placeholder="Email" required>
                </div>

                <div class="mb-3">
                        <label for="exampleFormControlTextarea1" class="form-label">Comments</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="10" name="message" placeholder="Comments"></textarea>
                </div>

           </form>


         </div>
    </div>

{% endblock %}

teachers/templates/edit.html
{% extends 'layout.html' %}

{% block body %}

    <title>Edit Student</title>


<div class="row container">
<div class="col-md-6">
    <br><br>
    <form action="" method="post" enctype="multipart/form-data">


        {% csrf_token %}


        <h2 class="p-3">Edit Student</h2>
        <div class="mb-3">
        <label  class="form-label">Name</label>
        <input type="text" class="form-control" name="name"  placeholder="Name"  value="name" required>
    </div>

    <div class="mb-3">
        <label  class="form-label">Email</label>
        <input type="text" class="form-control"  name="email" placeholder="Email" value="email" required>

    </div>

    <div class="mb-3">
        <label  class="form-label">Phone Number</label>
        <input type="number" class="form-control" name="phone"  placeholder="Number" value="phone" required>

    </div>

    <div class="mb-3">
        <label  class="form-label">image</label>
                    <img src="http://127.0.0.1:8000/media/{{ student.image }}" alt="{{ student.name }}" >

        <input accept="image/png, image/gif, image/jpeg" name="image" type="file" class="form-control"  placeholder="Add image" required>

    </div>

    <div class="mb-3">

        <button type="submit" name="button" class="form-control btn btn-success" >Submit</button>


    </div>

    </form>

</div>
</div>



{% endblock %}

teachers/templates/home.html
{% extends 'layout.html' %}


{% block body  %}
 <title>Home</title>


    <p>lkjhgvbnm,</p>

{% endblock %}

teachers/templates/layout.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


</head>
<body>


<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'teachers:home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item {% if navbar == 'home' %} active {% endif %}">
          <a  class="nav-link"  href="{% url 'teachers:home' %}">Home</a>
        </li>
        <li class="nav-item {% if navbar == 'about' %} active {% endif %}">
          <a class="nav-link" href="{% url 'teachers:about' %}">About</a>
         </li>
        <li class="nav-item {% if navbar == 'contact' %} active {% endif %}">
          <a class="nav-link" href="{% url 'teachers:contact' %}">Contact</a>
        </li>

         <li class="nav-item {% if navbar == 'addData' %} active {% endif %}">
          <a class="nav-link" href="{% url 'teachers:addData' %}">Add Data</a>
        </li>

         <li class="nav-item {% if navbar == 'viewdata' %} active {% endif %}">
          <a class="nav-link" href="{% url 'teachers:viewdata' %}">View Data</a>
        </li>

         <li class="nav-item {% if navbar == 'settings' %} active {% endif %}">
          <a class="nav-link" href="{% url 'settings:settings' %}">Settings</a>
        </li>

          <li class="nav-item {% if navbar == 'sliders' %} active {% endif %}">
          <a class="nav-link" href="{% url 'teachers:sliders' %}">Sliders</a>
        </li>

      </ul>
      <form class="d-flex" role="search" method="get" action="{% url 'teachers:search' %}" >
        <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block body %}

{% endblock %}

<footer>
    <nav class="navbar bg-success d-flex fixed-bottom justify-content-center text-center px-5">
  <div class="container-fluid text-center  px-5">
    <span class="navbar-brand mb-0 h1 d-flex justify-content-center text-center px-5">ndirangu creations</span>
  </div>
</nav>
</footer>

</body>
</html>

teachers/templates/search.html
{% extends 'layout.html' %}

{% block body %}


    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <br><br>

            <h2 class="p-3">Search Results</h2>

            {% if data  %}



            <h2>Students - Grid </h2>
            <div class="row">
                {% for student in data %}

                    <div class="col-md-3 " >

                    <div class="card">
                        <img src="http://127.0.0.1:8000/media/{{ student.image }}" class="card-img-top " alt="{{ student.name }} " >
                        <div class="card-body">
                            <h5 class="card-title">{{ student.name }}</h5>
                            <p class="card-text"> {{ student.email }}</p>

                        </div>
                    </div>

                    </div>

                {% endfor %}


            </div>


             {% else %}

               <h3 class="text-danger">No record matching your query was found</h3>

            {% endif %}





            </div>
        </div>
    </div>





{% endblock %}

teachers/templates/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <h2>Register</h2>


    <form action="" method="post">
        {% csrf_token %}

        {{ form.as_p }}
    </form>

</body>
</html>

teachers/templates/sliders.html
{% extends "layout.html" %}


{% block body %}



<div class="container">

    <div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">



     {% for slide in slides %}

    <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
      <img src="/media/{{ slide.image }}" class="d-block w-100 h-30" alt="{{ slide.text }}">
      <div class="carousel-caption d-none d-md-block">
        <h5>{{ slide.text }}</h5>
        <p>{{ slide.text1 }}</p>
      </div>
    </div>

      {% endfor %}


    </div>



  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div>

{% endblock %}

teachers/templates/viewdata.html
{% extends 'layout.html' %}

{% block body %}


    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <br><br>
{% if data %}
            <h2 class="p-3">Students</h2>

            {% for message in messages %}

                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>

            {% endfor %}



            	<table class="table " >
  <thead>
    <tr >
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
        <th scope="col">Image</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>

    </tr>
  </thead>
  <tbody>

  {% for student in data %}
  <tr>
      <th scope="row">{{ student.id }}</th>
      <td>{{ student.name }}</td>
      <td>{{ student.email }}</td>
      <td>{{ student.phone }}</td>
        <td>
            <img src="http://127.0.0.1:8000/media/{{ student.image }}" alt="{{ student.name }}" width="50">
        </td>
        <td>
            <a href="/edit/{{ student.id }}" class="btn btn-warning">Edit</a>
        </td>
        <td>
            <a href="/delete/{{ student.id }}" class="btn btn-danger">Delete</a>
        </td>
    </tr>
  {% endfor %}


  </tbody>
</table>

            <!--pagination-->

       <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">


            {% if data.has_previous %}

                <li class="page-item"><a class="page-link" href="?page=1">&laquo First</a></li>

                <li class="page-item"><a class="page-link" href="?page={{  data.previous_page_number }}">Previous</a></li>

            {% endif %}


          <li class="page-item disabled"><a class="page-link">Page {{ data.number }} of {{ data.paginator.num_pages }} </a></li>

            {% for i in nums %}

                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>

            {% endfor %}

          {% if data.has_next %}

                <li class="page-item"><a class="page-link" href="?page={{ data.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ data.paginator.num_pages }}">Last &raquo</a></li>

          {% endif %}

  </ul>
</nav>

            {% else %}

                <h3 class="text-warning">Sorry no records added yet</h3>
            {% endif %}


            </div>
        </div>
    </div>





{% endblock %}